# Generated by Django 3.0.8 on 2020-07-28 03:30

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200720_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
