# Generated by Django 3.0.8 on 2020-08-11 02:40

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_filename', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', s3direct.fields.S3DirectField(blank=True)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('pdf', s3direct.fields.S3DirectField(blank=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cat')),
            ],
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
