name: Test s3direct

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t s3direct

      - name: Test with Tox
        run: docker run -t s3direct tox
